//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/7 Input/UserActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Inca
{
    public partial class @UserActions: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @UserActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""UserActions"",
    ""maps"": [
        {
            ""name"": ""UserContol"",
            ""id"": ""efbc12b2-c09b-4336-93c3-a42a3ef32a5b"",
            ""actions"": [
                {
                    ""name"": ""Point"",
                    ""type"": ""Value"",
                    ""id"": ""e42bdf58-2c0c-4089-ad09-fcb36cb1254f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""cdbcc65b-51ce-44c4-815d-74fd8c82e2c8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c0017426-3c9d-4e60-8b0e-dd4694ee515e"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Monitor and Mouse"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d2f7f172-6936-4e4d-92fb-eaa4869ef3ae"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Monitor and Mouse"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Monitor and Mouse"",
            ""bindingGroup"": ""Monitor and Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Monitor and VR Controller"",
            ""bindingGroup"": ""Monitor and VR Controller"",
            ""devices"": [
                {
                    ""devicePath"": ""<XRController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // UserContol
            m_UserContol = asset.FindActionMap("UserContol", throwIfNotFound: true);
            m_UserContol_Point = m_UserContol.FindAction("Point", throwIfNotFound: true);
            m_UserContol_Click = m_UserContol.FindAction("Click", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // UserContol
        private readonly InputActionMap m_UserContol;
        private List<IUserContolActions> m_UserContolActionsCallbackInterfaces = new List<IUserContolActions>();
        private readonly InputAction m_UserContol_Point;
        private readonly InputAction m_UserContol_Click;
        public struct UserContolActions
        {
            private @UserActions m_Wrapper;
            public UserContolActions(@UserActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Point => m_Wrapper.m_UserContol_Point;
            public InputAction @Click => m_Wrapper.m_UserContol_Click;
            public InputActionMap Get() { return m_Wrapper.m_UserContol; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(UserContolActions set) { return set.Get(); }
            public void AddCallbacks(IUserContolActions instance)
            {
                if (instance == null || m_Wrapper.m_UserContolActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_UserContolActionsCallbackInterfaces.Add(instance);
                @Point.started += instance.OnPoint;
                @Point.performed += instance.OnPoint;
                @Point.canceled += instance.OnPoint;
                @Click.started += instance.OnClick;
                @Click.performed += instance.OnClick;
                @Click.canceled += instance.OnClick;
            }

            private void UnregisterCallbacks(IUserContolActions instance)
            {
                @Point.started -= instance.OnPoint;
                @Point.performed -= instance.OnPoint;
                @Point.canceled -= instance.OnPoint;
                @Click.started -= instance.OnClick;
                @Click.performed -= instance.OnClick;
                @Click.canceled -= instance.OnClick;
            }

            public void RemoveCallbacks(IUserContolActions instance)
            {
                if (m_Wrapper.m_UserContolActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IUserContolActions instance)
            {
                foreach (var item in m_Wrapper.m_UserContolActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_UserContolActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public UserContolActions @UserContol => new UserContolActions(this);
        private int m_MonitorandMouseSchemeIndex = -1;
        public InputControlScheme MonitorandMouseScheme
        {
            get
            {
                if (m_MonitorandMouseSchemeIndex == -1) m_MonitorandMouseSchemeIndex = asset.FindControlSchemeIndex("Monitor and Mouse");
                return asset.controlSchemes[m_MonitorandMouseSchemeIndex];
            }
        }
        private int m_MonitorandVRControllerSchemeIndex = -1;
        public InputControlScheme MonitorandVRControllerScheme
        {
            get
            {
                if (m_MonitorandVRControllerSchemeIndex == -1) m_MonitorandVRControllerSchemeIndex = asset.FindControlSchemeIndex("Monitor and VR Controller");
                return asset.controlSchemes[m_MonitorandVRControllerSchemeIndex];
            }
        }
        public interface IUserContolActions
        {
            void OnPoint(InputAction.CallbackContext context);
            void OnClick(InputAction.CallbackContext context);
        }
    }
}
